### PR TITLE
feat: events support on creating elements

### LINKED ISSUE #46: `vueuse/head` doesn't support events when creating an element
Hi everybody.
I recently worked on new features that bring [script loading strategy](https://github.com/nuxt/framework/discussions/2342) to the Nuxt. The problem is when I add some events to the `script` component (provided by nuxt as sugar syntax of useMeta), it turned into attributes and prints the event function string on the element.

```html
<script src="./mock.js?t=49" strategy="immediate" onload="function() { console.log('loaded')"></script>
```

### PR DESCRIPTION
**Pull request by ms-fadaei**
Resolve #46

### CODE REVIEW

**Comment by ms-fadaei** [comment]
Big Question: how we can add event listeners to server-side rendered scripts on hydration?

**Comment by egoist** [comment]
should continue to make a normal attribute if the value is a string

**Comment by egoist** [comment]
> Big Question: how we can add event listeners to server-side rendered scripts on hydration?

there's no need to server-side render the `<Script />` component I guess

**Comment by ms-fadaei** [comment]
> there's no need to server-side render the `<Script />` component I guess
Sometimes we need our script load as soon as possible. This strategy should be used for any critical scripts that need to be fetched and executed before the page is interactive.

**Comment by ms-fadaei** [comment]
> should continue to make a normal attribute if the value is a string so `onload: "console.log('loaded')"` will still work

Yes of course. But closure will not work!

**Comment by egoist** [comment]
well it seems next.js just ignores `onLoad` prop when the strategy is `beforeInteractive`

**Comment by ms-fadaei** [comment]
> well it seems next.js just ignores onLoad prop when the strategy is beforeInteractive, which is also ssr-ed, otherwise that script is created on the client-side only

I didn't test this on real example but in the docs, [it mentioned](https://nextjs.org/docs/basic-features/script#executing-code-after-loading-onload) we could use onLoad

**Comment by egoist** [comment]
https://stackblitz.com/edit/nextjs-wt4j8y?file=pages%2Findex.js maybe a bug then

**Comment by ms-fadaei** [comment]
What I worrying about is maybe the event won't be triggered  because they already loaded if (this is a big if) we add listeners on hydration

**Comment by egoist** [comment]
the listener won't be triggered on hydration because we won't recreate the element to avoid loading it twice:

https://github.com/vueuse/head/blob/5ef9b6225e6c70e18011c33fb77d67de11af0d26/src/index.ts#L198-L201

but maybe we call `newEl.onload` manually if  `oldEl.onload` is `undefined`

**Comment by ms-fadaei** [comment]
> the listener won't be triggered on hydration because we won't recreate the element to avoid loading it twice:

I looking for a way to attach the event to the existing element.
But if find a way to do that, we can't be sure it will be called!!!
I tried some ways already but they results in recreating.

**Comment by ms-fadaei** [comment]
@egoist Hi again!

I tried a lot of ways and couldn't find a clear and straightforward way!
I think a lot about it and what we did in Nuxt 2 and find out we really don't need to attach event listeners to the SSR script. They just load and evaluate as to their order of definition. 

I also think the Next documentation has some mistakes. Maybe they wanted to mention `afterInteractive` and `lazyOnload`

**Comment by ms-fadaei** [comment]
I will be very thankful if you merge this PR 🙏

**Comment by ms-fadaei** [comment]
@egoist 
Please let me know can we merge this PR or not?

**Comment by davodaslanifakor** [comment]
Hey @egoist.
I'll be looking forward to this feature. If everything is fine, please finish it.

**Comment by mathieumagalhaes** [comment]
I've tested this locally with onload on script tags, everything seems to be working just fine
It has been multiple months and a non-breaking change, can this be merged in @egoist @ms-fadaei ?

**Comment by harlan-zw** [comment]
`value` would now be HTML encoded so any scripts would likely not work, otherwise this may introduce XSS issues for users

Could possibly implement this with https://github.com/vueuse/head/issues/95

Will close for now as the PR seems stale, but please comment on the above issue if you agree with the direction

**Pull request closed without merging**
