### PR TITLE
fix: improved deduping for `charset`, `base`, `link`, etc

### PR DESCRIPTION
**Pull request by harlan-zw**
See #64, #32

The solution is to modify the dedupe key function to provide more explicit instructions on how the tag should be deduped.

### CODE REVIEW

**Comment by antfu** [comment]
Could you help resolving the conflicts? Thanks

**Review by antfu — APPROVED** [review]

**Comment by harlan-zw** [comment]
Thanks for the review @antfu!

Conflict is resolved in this PR

**Comment by antfu** [comment]
🤣 conflicts again :P

**Comment by harlan-zw** [comment]
Hm I think because I merged this branch into the other one, thinking that you'd merge this one first :P 

So I'll close this because the code is in main now

**Pull request closed without merging**
